import { Request, Response } from "express";
import { UserService } from "../services/user.services";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";

const JWT_SECRET = process.env.JWT_SECRET || "change_this_secret";

export class AuthController {
  private userService = new UserService();

  async register(req: Request, res: Response) {
    try {
      const { name, email, password } = req.body;
      if (!name || !email || !password)
        return res.status(400).json({ message: "Missing fields" });

      const existing = await this.userService.getUserByEmail(email);
      if (existing) return res.status(409).json({ message: "Email in use" });

      const hashed = await bcrypt.hash(password, 10);
      // id is auto-generated by DB
      await this.userService.createUser({
        name,
        email,
        password: hashed,
        role: false,
      });
      return res.status(201).json({ message: "User registered" });
    } catch (error) {
      console.error(error);
      return res.status(500).json({ message: "Error registering user" });
    }
  }

  async login(req: Request, res: Response) {
    try {
      const { email, password } = req.body;
      if (!email || !password)
        return res.status(400).json({ message: "Missing email or password" });

      const user = await this.userService.getUserByEmail(email);
      if (!user)
        return res.status(401).json({ message: "Invalid credentials" });

      if (!user.password) {
        console.error("User found but has no password hash stored:", email);
        return res.status(500).json({ message: "Account error" });
      }

      const ok = await bcrypt.compare(password, user.password);
      if (!ok) return res.status(401).json({ message: "Invalid credentials" });

      const payload = {
        idUser: user.idUser,
        email: user.email,
        role: user.role,
      };
      const token = jwt.sign(payload, JWT_SECRET, { expiresIn: "8h" });
      return res.status(200).json({
        token,
        user: {
          idUser: user.idUser,
          name: user.name,
          email: user.email,
          role: user.role,
        },
      });
    } catch (error: any) {
      console.error("Login error:", error);
      return res
        .status(500)
        .json({ message: "Error logging in", error: error.message });
    }
  }

  // -------------------------------------------------------
  // password recovery endpoints
  // -------------------------------------------------------

  /**
   * initiate password reset by email
   * returns a token (in real app would email the link)
   */
  async forgotPassword(req: Request, res: Response) {
    try {
      const { email } = req.body;
      if (!email) return res.status(400).json({ message: "Email required" });

      const user = await this.userService.getUserByEmail(email);
      // always respond successfully to avoid leaking which emails exist
      if (!user) {
        return res.status(200).json({
          message: "If that email is registered, a reset link has been sent",
        });
      }

      const token = jwt.sign({ idUser: user.idUser }, JWT_SECRET, {
        expiresIn: "1h",
      });
      // TODO: send token to user via email. For now we return it for testing
      console.log(`Password reset token for ${email}: ${token}`);
      return res.status(200).json({ message: "Reset token generated", token });
    } catch (err) {
      console.error("forgotPassword error", err);
      return res.status(500).json({ message: "Error processing request" });
    }
  }

  /**
   * complete password reset using token
   */
  async resetPassword(req: Request, res: Response) {
    try {
      const { token, newPassword } = req.body;
      if (!token || !newPassword) {
        return res
          .status(400)
          .json({ message: "Token and new password required" });
      }

      let payload: any;
      try {
        payload = jwt.verify(token, JWT_SECRET) as any;
      } catch (err) {
        return res.status(400).json({ message: "Invalid or expired token" });
      }

      const user = await this.userService.getUserById(payload.idUser);
      if (!user) {
        return res.status(404).json({ message: "User not found" });
      }

      const hashed = await bcrypt.hash(newPassword, 10);
      await this.userService.updateUser(user.idUser, { password: hashed });
      return res.status(200).json({ message: "Password has been reset" });
    } catch (err) {
      console.error("resetPassword error", err);
      return res.status(500).json({ message: "Error resetting password" });
    }
  }
}

export default new AuthController();
